### ISSUE TITLE
Need more info on creating custom rules

### ISSUE THREAD

**Issue by lesaff** [naifalshaye/nova-random-password-generation#4]
Hi, thanks for creating a much-needed field for Nova. I am trying to customize how it generates password rule (excluded characters, etc) but couldn't find anything on your docs.

Cheers,

**Comment by naifalshaye** [comment]
Dear @lesaff excluded password characters types feature is implemented. 
I hope it's what you needed.

BR,
Naif

**Comment by lesaff** [comment]
Awesome! Thanks, much appreciated.

Rudy

**Comment by naifalshaye** [comment]
Glad you like it
